name: build
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler: latest
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
    - name: Report coverage
      uses: devmasx/coverage-check-action@v1.2.0
      with:
        type: simplecov
        result_path: coverage/.last_run.json
        min_coverage: 85
        token: ${{ github.token }}
